package exceptionThrown;

public class TestException {
    public static void main(String[] args) {
        System.out.println("Program started");
        int a = 15/0;
        System.out.println("Program End");
    }
}
